### ISSUE TITLE
Encountered error while generating package metadata

### ISSUE THREAD

**Issue by Maria-C1** [yasserqureshi1/power-of-10#1]
errors when running the command `pip install power-of-10==0.0.1`
thought it was the old NumPy version but still get errors after updating this.

![Po10 image](https://user-images.githubusercontent.com/93196464/184350321-343f4917-94ba-4cd8-a81f-3a9d21fe9fe3.png)

**Comment by yasserqureshi1** [comment]
@Maria-C1 What Python version are you using? I've only tested this with Python 3.8
